dataset_name: contract_nli_limited_use
include: ../multiple_choice_template_yaml
task: legalbench_contract_nli_limited_use_multiple_choice
group: 
 - legalbench_exact_match
 - legalbench_INTERPRETATION_TASKS
