dataset_name: contract_nli_sharing_with_third-parties
include: ../multiple_choice_template_yaml
task: legalbench_contract_nli_sharing_with_third-parties_multiple_choice
group: 
 - legalbench_exact_match
 - legalbench_INTERPRETATION_TASKS
