dataset_name: contract_nli_survival_of_obligations
include: ../multiple_choice_template_yaml
task: legalbench_contract_nli_survival_of_obligations_multiple_choice
group: 
 - legalbench_exact_match
 - legalbench_INTERPRETATION_TASKS