dataset_name: cuad_revenue-profit_sharing
include: ../multiple_choice_template_yaml
task: legalbench_cuad_revenue-profit_sharing_multiple_choice
group: 
  - legalbench_exact_match
  - legalbench_INTERPRETATION_TASKS