dataset_name: cuad_warranty_duration
include: ../multiple_choice_template_yaml
task: legalbench_cuad_warranty_duration_multiple_choice
group: 
  - legalbench_exact_match
  - legalbench_INTERPRETATION_TASKS