dataset_name: learned_hands_domestic_violence
include: ../multiple_choice_template_yaml
task: legalbench_learned_hands_domestic_violence_multiple_choice
group: 
  - legalbench_exact_match
  - legalbench_ISSUE_TASKS