dataset_name: maud_change_in_law__subject_to_disproportionate_impact_modifier
include: ../multiple_choice_template_yaml
task: legalbench_maud_change_in_law__subject_to_disproportionate_impact_modifier_multiple_choice
group: 
  - legalbench_exact_match
  - legalbench_INTERPRETATION_TASKS