dataset_name: maud_financial_point_of_view_is_the_sole_consideration
include: ../multiple_choice_template_yaml
task: legalbench_maud_financial_point_of_view_is_the_sole_consideration_multiple_choice
group: 
  - legalbench_exact_match
  - legalbench_INTERPRETATION_TASKS